name: Roda o Web Scraper de Vagas

on:
  workflow_dispatch: # Permite rodar manualmente
  schedule:
    - cron: '0 8 * * *' # Roda todo dia às 8h da manhã (fuso UTC)

jobs:
  scrape:
    runs-on: ubuntu-latest
    steps:
      - name: Checar o código do repositório
        uses: actions/checkout@v3

      - name: Configurar Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11' # Use a versão do seu projeto

      - name: Instalar dependências (usando pip por simplicidade no Actions)
        run: |
          python -m pip install --upgrade pip
          pip install requests beautifulsoup4 pandas
          
      - name: Executar o Scraper
        run: python scraper.py

      - name: Fazer o commit do novo arquivo de dados
        run: |
          git config --global user.name 'GitHub Actions Bot'
          git config --global user.email 'actions@github.com'
          git add vagas_dados.csv
          # Apenas faz commit se houver alguma mudança no arquivo
          git diff --quiet && git diff --staged --quiet || git commit -m "Atualiza dados de vagas"
          git push